unique_ids:
  forms:
    Customers.Accounts.AccountsTable.RowTemplate1: '1661925312421180895085058.14743'
    Dashboard.Content.RowTemplate5: '1686043400383166726421809.0958'
    Dashboard.Content.HeadlineStats: DBWU2UQRC5GEM6PJNRKRYECNWVZYJ5DC
    Customers.Account: DZZRU7BXIPD2UYJPYNYNPQIQLSTX65SH
    Settings.Settings.SettingsMain: '1674865654002360699636164.9306'
    Tickets.Transaction: DVHICGP2CGK5DCPO3VCFWL5N3JRUEKIC
    Tickets.Transaction.TransactionEntries: '1716351811695359118225362.86285'
    Tickets.NewTransaction: XH6LDF5WVYZRBY7L6ZW7RN4JDIFFIC7E
    Icons.PlusSVG: IVMAD7XGG6PJ7NQWCP7YDBNVOIA2UDMX
    Homepage: 2A5ZUAWFZ76KHXWMLI4UL5X5JRKVIE64
    Tickets.NewTransaction.Account.AccountSearchRow: NEGSCLBIAAP6A7CE4R43M2GUQDSN4RBO
    Icons.Avatar: 4DCDFMYDMTKN5WJJZ2N332F62ALVUVN3
    Login: JDYKL2RICYLHXITPFUPGVYXDTXGH5C36
    Icons.AvatarBlank: UDWDECOYX5HF6CJQHL4EKPHHG6RD4E6E
    Settings.Settings.SettingsMain.RowTemplate4: '1675068084224528433692608.88196'
    Tickets.NewTransaction.Account: ZALF5NHVB7K5235CXNSWY7PEYCXASBJY
    Icons.SignOutSVG: RZUD2LBSBPGW4DOQTZPSQ2KPC4W5UITV
    Icons.AvatarSmall: 3QHVTU7ZVNCFXCUQE6JUX6SPSAFNTIXC
    Dashboard: 34APWRYJM4ZU7VGLI5MRB7IWCIKAARRW
    Customers.Accounts_old.Letter: NN376W7A6352RSBEWV2CG4BLAYGCCPHQ
    Icons.SearchSVG: B27LUPSJRMWGHKIXZUPBK2C267AATO2L
    Icons.AvatarTransparent: WKFPCBDU4WB77THFB6BVJSJ4NAYDOKVL
    Icons.TicketsSVG: W3BE7TX5LHPIUQO7HRQCGXUURNHMZ2LH
    Customers.Accounts_old.Table: ARMDKQ22MRLARMTLBSAYJRCW3ECRCBLD
    Customers.Account.NewAccount: '1675764484917627040103314.976'
    Analyse.Analyse.AnalyseHeader: '1690365064811287403021592.84827'
    Dashboard.Content: SBZ46LNCXFIYVOS33Z4DSAGXK7EZXTK4
    Customers.Accounts.AccountsTable: '1661925281790969316828896.063'
    Icons.DashboardSVG: LGW7AVIRIEPZTD5SSSCFCAYTFG37DQ5A
    Customers.Account.AccountTransactions.AccountTransactionRow: '1662265965015570875132453.8544'
    Settings.Settings.SettingsDetails: '1690082255085177853874105.2671'
    Analyse.Analyse: '1690364818339341842406025.8613'
    Customers.AccountDetailsOverlay: VVO2NEKRJVDLMIQDH4JA4NN45W6G7K5T
    Settings.Settings: '1674865567914624700277131.2924'
    Customers.Account.AccountTransactions: '1662265917166855251234822.4473'
    Settings.Settings.SettingsMain.RowTemplate3: '1674867718770291360982029.5187'
    Tickets.Transactions.TransactionList.TransactionRow: 4J3ZNGMN6CQ6AKDQCLQQM33STW5IBQGM
    Analyse.Analyse.AnalyseContent: '1690365794367893314728542.7845'
    Tickets.Transactions.TransactionList: PKKAQMZOAPITDOFK6PKTUH7PF5JHNSHV
    Icons.CustomersSVG: JSXDYS3OS6KLIEZNUPM6CCUUHZENX2NC
    Customers.Accounts: '1662968543525380878179473.1249'
    Users.Users: '1717199200565176742420247.8882'
    Customers.Account.Details.RecentTransactions: O3G5TAV2KGVUFUBXOFAF2O6ZQ5I4JMOL
    Dashboard.Content.ResolutionGraph: QVXXXCK3FDUSRPTRTAPREU2FSKHG5XCU
    Customers.Account.Details: MTBWN57RVD7GAHIRJQC4DKDYRPJ6OPYG
    Tickets.NewTransaction.Details: A2OXFXFEWZIAPKIODKXOYOODQ2WRPHT7
    Icons.UserSVG: NI576LNCUZ45YC3DKHC2FO2HLQAJQEKS
    Customers.Accounts_old: ISUS26YLIASQ7X4GGL65SXMWYJA53RMO
    Customers.Accounts_old.Table.LetterGroup.AccountRow: JP5CWTEXV73HGREB7UY2NWZTGYSQT7XS
    Icons.SettingsSVG: X7DJOVAJKCOZLHV2IN25FZLJ7NRZYB5S
    Dashboard.Content.ProgressGraph: KF27O6AROR3ACC5V76XKCDK27P6QVPIG
    Tickets.Transactions: OMTOI2RTLP4EYI543MFTDRRQ6UAEF4XL
    Customers.Accounts_old.Table.LetterGroup: PUKRB6SOCXLNRHUKXSEU6ILZJHCANO56
  modules:
    Analyse: '1690364798641300362083064.7682'
    Tickets.TransactionsModule: '1631202249424390320128286.3753'
    Tickets: FMNBXOD55PJCJFUOX4FCXJ2XCJIIGYBB
    Validation: 7UQAU5SOZHFBG2RZKBL7BOJJKTMGSZ3E
    Icons: 34IHCE7JGHUKBCH76JGASJMGJN7RQXZP
    Customers: O34FSKGU5GCFN5OB3QFXLDIQOEM5JPXV
    Settings: '1674865546907837476874104.1207'
    Users: '1717199098980289492968764.5931'
    Data: RRMBYYNWGVQITJ4PQYTLQHRROUOJ3RB7
  server_modules:
    ServerModule1: WFPN7MUXJ6HJRWQ45JDSDYPJXQWC6AML
  assets:
    grey-background.png: CRJOABJO4QRYO7Y2ZQRKMP4CWZ4IRBFJ
    theme.css: WWBYXJWL7KHSM77MEFA534ZP2RWJ2IJ4
    digital-money-technology-logo-vector_new.jpg: '1715995975898794541621980.6311'
    spinner.png: OVUKAUSCX6TZ7HPJJKU2E2TJPJKQRDHY
    three_slot_overlay.html: QBBKFYUFPCYXQ4P3A6LXCL2TUZAD3GTB
    digital-money-technology-logo-vector.jpg: '1715995858562521219418252.8338'
    flex_col_three_slots_wide.html: '1690424486662617921671951.1888'
    flex_col_three_slots.html: UOXNAVRKTFBUZSDUX73T7IFYWTXUXUKK
    grey-box.png: RJE2TUXLEYCPJN2G3KN46P7OQJSVS263
    grey-squiggles.png: DGGP4E3HFMVN6CHSTPC6E5C35LCIIR4U
    JB_AU.png: '1716519093633527283187971.153'
    chev.png: MSWCMCAGL5LDNX5FHSFDPYYWG3L3GFKF
    three_slots.html: UVQ2Y3IEG3RNVXC4PJGEYJHS5HRPK64Y
    homepage.html: ILSPFDLJ4RIH5C7G23ATFYVYK26J7NUY
    two_slots_customers.html: XF4UOQCCFVHUOIF6CBGCIXDZCR6L5V2E
    down-arrow.png: SM4B2WZANYKXXFI4JJRC6TNMFVVHRSFW
    chevron.png: SCU5N47N3GZRGACTFN23MH3FXFZDECQX
    scroll_pane.html: RE5UEL22CRXKQ4EWKXU44RO7L4IVWZGQ
    user.svg: RCDK6LNABNOMNJOUV3VKYSUOJOA7ST6N
    purple-search.png: KGFNCCYLXX2YJWILDAAV3AERTVY6WYWD
    JB_NZ.png: '1716522083375417457931110.37054'
    TGG.png: '1716522093715977968758498.158'
    up-arrow.png: VM43M2QYV4WORR5M3LFYVKLHZXKGTRSW
    one_slot_overlay.html: Q4E67QTREWFSIHWVCKQUAOQQASVK5CT5
    three_slot_wide.html: '169018030632860257027515.82984'
  scripts: {}
